// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDqY4gBTYs6jOw6OBQb7Q4pM17GA_j0Y',
    appId: '1:966174867610:web:f58b613e30c3c417235f23',
    messagingSenderId: '966174867610',
    projectId: 'notes-daily-task',
    authDomain: 'notes-daily-task.firebaseapp.com',
    storageBucket: 'notes-daily-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATAW0ERi-KcyjZFztXPxJG0pr0YhPdEKA',
    appId: '1:966174867610:android:5bd9e8e42f1d6311235f23',
    messagingSenderId: '966174867610',
    projectId: 'notes-daily-task',
    storageBucket: 'notes-daily-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCydlJOYDgn4QT1FDLKOM2VpAQikaK_7lg',
    appId: '1:966174867610:ios:d886af0cfc26f631235f23',
    messagingSenderId: '966174867610',
    projectId: 'notes-daily-task',
    storageBucket: 'notes-daily-task.appspot.com',
    iosClientId: '966174867610-a00f1hcprla577tgln8koaniq7tpfq1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
